
package com.cware.api.panaver.product.type;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 03:56 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebService(name = "AddressBookServicePortType", targetNamespace = "http://shopn.platform.nhncorp.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AddressBookServicePortType {



    /**
     * 
     * @param getAddressBookListRequest
     * @return
     *     returns com.nbp.nmp.shopn.getAddressBookListResponseType
     */
    @WebMethod(operationName = "GetAddressBookList", action = "AddressBookService#GetAddressBookList")
    @WebResult(name = "GetAddressBookListResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetAddressBookListResponse")
    public GetAddressBookListResponseType getAddressBookList(
        @WebParam(name = "GetAddressBookListRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetAddressBookListRequest")
        GetAddressBookListRequestType getAddressBookListRequest);

}
