
package com.cware.api.panaver.product.type;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import com.cware.netshopping.common.util.ConfigUtil;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 03:56 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AddressBookService", targetNamespace = "http://shopn.platform.nhncorp.com/", wsdlLocation = "file:///home/himuleo/work/productapi-sample/src/main/resources/ShopNAPI.wsdl")
public class AddressBookService
    extends Service
{

    private final static URL ADDRESSBOOKSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
        	url = new URL(ConfigUtil.getString("PANAVER_SERVICE_WSDL")); 
        	
        	//로컬
//        	url = new URL("http://1.255.85.244:8443/paApi/naver/dev/ShopNAPI.wsdl");            
            //운영
//          url = new URL("http://devpc.skstoa.com/panaver/real/ShopNAPI.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        ADDRESSBOOKSERVICE_WSDL_LOCATION = url;
    }

    public AddressBookService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AddressBookService() {
        super(ADDRESSBOOKSERVICE_WSDL_LOCATION, new QName("http://shopn.platform.nhncorp.com/", "AddressBookService"));
    }

    /**
     * 
     * @return
     *     returns AddressBookServicePortType
     */
    @WebEndpoint(name = "AddressBookServiceSOAP11port_http")
    public AddressBookServicePortType getAddressBookServiceSOAP11PortHttp() {
        return (AddressBookServicePortType)super.getPort(new QName("http://shopn.platform.nhncorp.com/", "AddressBookServiceSOAP11port_http"), AddressBookServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AddressBookServicePortType
     */
    @WebEndpoint(name = "AddressBookServiceSOAP11port_http")
    public AddressBookServicePortType getAddressBookServiceSOAP11PortHttp(WebServiceFeature... features) {
        return (AddressBookServicePortType)super.getPort(new QName("http://shopn.platform.nhncorp.com/", "AddressBookServiceSOAP11port_http"), AddressBookServicePortType.class, features);
    }

    /**
     * 
     * @return
     *     returns AddressBookServicePortType
     */
    @WebEndpoint(name = "AddressBookServiceSOAP12port_http")
    public AddressBookServicePortType getAddressBookServiceSOAP12PortHttp() {
        return (AddressBookServicePortType)super.getPort(new QName("http://shopn.platform.nhncorp.com/", "AddressBookServiceSOAP12port_http"), AddressBookServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AddressBookServicePortType
     */
    @WebEndpoint(name = "AddressBookServiceSOAP12port_http")
    public AddressBookServicePortType getAddressBookServiceSOAP12PortHttp(WebServiceFeature... features) {
        return (AddressBookServicePortType)super.getPort(new QName("http://shopn.platform.nhncorp.com/", "AddressBookServiceSOAP12port_http"), AddressBookServicePortType.class, features);
    }

}
