
package com.cware.api.panaver.product.type;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 03:56 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DeliveryInfoServicePortType", targetNamespace = "http://shopn.platform.nhncorp.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DeliveryInfoServicePortType {



    /**
     * 
     * @param GetBundleGroupRequest
     * @return
     *     returns com.nbp.nmp.shopn.getBundleGroupResponseType
     */
    @WebMethod(operationName = "GetBundleGroup", action = "DeliveryInfoService#GetBundleGroup")
    @WebResult(name = "GetBundleGroupResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetBundleGroupResponse")
    public GetBundleGroupResponseType getBundleGroup(
        @WebParam(name = "GetBundleGroupRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetBundleGroupRequest")
        GetBundleGroupRequestType getBundleGroupRequest);

    /**
     * 
     * @param GetBundleGroupListRequest
     * @return
     *     returns com.nbp.nmp.shopn.getBundleGroupResponseType
     */
    @WebMethod(operationName = "GetBundleGroupList", action = "DeliveryInfoService#GetBundleGroupList")
    @WebResult(name = "GetBundleGroupListResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetBundleGroupListResponse")
    public GetBundleGroupListResponseType getBundleGroupList(
        @WebParam(name = "GetBundleGroupListRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetBundleGroupListRequest")
        GetBundleGroupListRequestType getBundleGroupListRequest);
    

    /**
     * 
     * @param GetReturnsCompanyListRequest
     * @return
     *     returns com.nbp.nmp.shopn.getBundleGroupResponseType
     */
    @WebMethod(operationName = "GetReturnsCompanyList", action = "DeliveryInfoService#GetReturnsCompanyList")
    @WebResult(name = "GetReturnsCompanyListResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetReturnsCompanyListResponse")
    public GetReturnsCompanyListResponseType getReturnsCompanyList(
        @WebParam(name = "GetReturnsCompanyListRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetReturnsCompanyListRequest")
        GetReturnsCompanyListRequestType getReturnsCompanyListRequest);
    
    

}
