
package com.cware.api.panaver.product.type;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 03:56 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ProductServicePortType", targetNamespace = "http://shopn.platform.nhncorp.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductServicePortType {


    /**
     * 
     * @param manageOptionRequest
     * @return
     *     returns com.nbp.nmp.shopn.ManageOptionResponseType
     */
    @WebMethod(operationName = "ManageOption", action = "ProductService#ManageOption")
    @WebResult(name = "ManageOptionResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "ManageOptionResponse")
    public ManageOptionResponseType manageOption(
        @WebParam(name = "ManageOptionRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "ManageOptionRequest")
        ManageOptionRequestType manageOptionRequest);

    /**
     * 
     * @param manageProductRequest
     * @return
     *     returns com.nbp.nmp.shopn.ManageProductResponseType
     */
    @WebMethod(operationName = "ManageProduct", action = "ProductService#ManageProduct")
    @WebResult(name = "ManageProductResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "ManageProductResponse")
    public ManageProductResponseType manageProduct(
        @WebParam(name = "ManageProductRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "ManageProductRequest")
        ManageProductRequestType manageProductRequest);
    
    /**
     * 
     * @param getAllCategoryListRequest
     * @return
     *     returns com.nbp.nmp.shopn.GetAllCategoryListResponseType
     */
    @WebMethod(operationName = "GetAllCategoryList", action = "ProductService#GetAllCategoryList")
    @WebResult(name = "GetAllCategoryListResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetAllCategoryListResponse")
    public GetAllCategoryListResponseType getAllCategoryList(
        @WebParam(name = "GetAllCategoryListRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetAllCategoryListRequest")
        GetAllCategoryListRequestType getAllCategoryListRequest);
    
    /**
     * 
     * @param getAllOriginAreaListRequestType
     * @return
     *     returns com.nbp.nmp.shopn.GetAllOriginAreaListResponseType
     */
    @WebMethod(operationName = "GetAllOriginAreaList", action = "ProductService#GetAllOriginAreaList")
    @WebResult(name = "GetAllOriginAreaListResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetAllOriginAreaListResponse")
    public GetAllOriginAreaListResponseType getAllOriginAreaList(
        @WebParam(name = "GetAllOriginAreaListRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetAllOriginAreaListRequest")
        GetAllOriginAreaListRequestType getAllOriginAreaListRequest);

    /**
     * 
     * @param GetModelListRequestType
     * @return
     *     returns com.nbp.nmp.shopn.GetModelListRequestType
     */
    @WebMethod(operationName = "GetModelList", action = "ProductService#GetModelList")
    @WebResult(name = "GetModelListResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetModelListResponse")
    public GetModelListResponseType getModelList(
        @WebParam(name = "GetModelListRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetModelListRequest")
        GetModelListRequestType getModelListRequest);

    /**
     * 
     * @param GetCategoryInfoRequestType
     * @return
     *     returns com.nbp.nmp.shopn.GetCategoryInfoRequestType
     */
    @WebMethod(operationName = "GetCategoryInfo", action = "ProductService#GetCategoryInfo")
    @WebResult(name = "GetCategoryInfoResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetCategoryInfoResponse")
    public GetCategoryInfoResponseType getCategoryInfo(
        @WebParam(name = "GetCategoryInfoRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetCategoryInfoRequest")
        GetCategoryInfoRequestType getCategoryInfoRequest);

    /**
     * 
     * @param GetSubCategoryListRequestType
     * @return
     *     returns com.nbp.nmp.shopn.GetSubCategoryListRequestType
     */
    @WebMethod(operationName = "GetSubCategoryList", action = "ProductService#GetSubCategoryList")
    @WebResult(name = "GetSubCategoryListResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetSubCategoryListResponse")
    public GetSubCategoryListResponseType getSubCategoryList(
        @WebParam(name = "GetSubCategoryListRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetSubCategoryListRequest")
        GetSubCategoryListRequestType getSubCategoryListRequest);

    /**
     * 
     * @param GetBrandListRequestType
     * @return
     *     returns com.nbp.nmp.shopn.GetBrandListRequestType
     */
    @WebMethod(operationName = "GetBrandList", action = "ProductService#GetBrandList")
    @WebResult(name = "GetBrandListResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetBrandListResponse")
    public GetBrandListResponseType getBrandList(
        @WebParam(name = "GetBrandListRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetBrandListRequest")
        GetBrandListRequestType getBrandListRequest);

    /**
     * 
     * @param GetBrandListRequestType
     * @return
     *     returns com.nbp.nmp.shopn.GetBrandListRequestType
     */
    @WebMethod(operationName = "GetManufacturerList", action = "ProductService#GetManufacturerList")
    @WebResult(name = "GetManufacturerListResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetManufacturerListResponse")
    public GetManufacturerListResponseType getManufacturerList(
        @WebParam(name = "GetManufacturerListRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetManufacturerListRequest")
        GetManufacturerListRequestType getManufacturerListRequest);
    
    /**
     * 
     * @param getSubOriginAreaListRequestType
     * @return
     *     returns com.nbp.nmp.shopn.GetSubOriginAreaListResponseType
     */
    @WebMethod(operationName = "GetSubOriginAreaList", action = "ProductService#GetSubOriginAreaList")
    @WebResult(name = "GetSubOriginAreaListResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetSubOriginAreaListResponse")
    public GetSubOriginAreaListResponseType getSubOriginAreaList(
        @WebParam(name = "GetSubOriginAreaListRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetSubOriginAreaListRequest")
        GetSubOriginAreaListRequestType getSubOriginAreaListRequest);
    
    /**
     * 
     * @param getOriginAreaListRequestType
     * @return
     *     returns com.nbp.nmp.shopn.GetOriginAreaListResponseType
     */
    @WebMethod(operationName = "GetOriginAreaList", action = "ProductService#GetOriginAreaList")
    @WebResult(name = "GetOriginAreaListResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetOriginAreaListResponse")
    public GetOriginAreaListResponseType getOriginAreaList(
        @WebParam(name = "GetOriginAreaListRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetOriginAreaListRequest")
        GetOriginAreaListRequestType getOriginAreaListRequest);

    /**
     * 
     * @param getProductListRequestType
     * @return
     *     returns com.nbp.nmp.shopn.GetProductListResponseType
     */
    @WebMethod(operationName = "GetProductList", action = "ProductService#GetProductList")
    @WebResult(name = "GetProductListResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetProductListResponse")
    public GetProductListResponseType getProductList(
        @WebParam(name = "GetProductListRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetProductListRequest")
        GetProductListRequestType getProductListRequest);

    /**
     * 
     * @param getProductListRequestType
     * @return
     *     returns com.nbp.nmp.shopn.GetProductListResponseType
     */
    @WebMethod(operationName = "GetMobileImageInfo", action = "ProductService#GetMobileImageInfo")
    @WebResult(name = "GetMobileImageInfoResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetMobileImageInfoResponse")
    public GetMobileImageInfoResponseType getMobileImageInfo(
        @WebParam(name = "GetMobileImageInfoRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetMobileImageInfoRequest")
        GetMobileImageInfoRequestType getMobileImageInfoRequest);

    /**
     * 
     * @param getProductListRequestType
     * @return
     *     returns com.nbp.nmp.shopn.GetProductListResponseType
     */
    @WebMethod(operationName = "GetProduct", action = "ProductService#GetProduct")
    @WebResult(name = "GetProductResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetProductResponse")
    public GetProductResponseType getProduct(
        @WebParam(name = "GetProductRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetProductRequest")
        GetProductRequestType getProductRequest);

    /**
     * 
     * @param getOptionListRequestType
     * @return
     *     returns com.nbp.nmp.shopn.getOptionListResponseType
     */
    @WebMethod(operationName = "GetOption", action = "ProductService#GetOption")
    @WebResult(name = "GetOptionResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetOptionResponse")
    public GetOptionResponseType getOption(
        @WebParam(name = "GetOptionRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetOptionRequest")
        GetOptionRequestType getOptionRequest);

//    /**
//     * 
//     * @param getModificationRequiredProductListRequestType
//     * @return
//     *     returns com.nbp.nmp.shopn.getModificationRequiredProductListResponseType
//     */
//    @WebMethod(operationName = "GetModificationRequiredProductList", action = "ProductService#GetModificationRequiredProductList")
//    @WebResult(name = "GetModificationRequiredProductListResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetModificationRequiredProductListResponse")
//    public GetModificationRequiredProductListResponseType getModificationRequiredProductList(
//        @WebParam(name = "GetModificationRequiredProductListRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetModificationRequiredProductListRequest")
//        GetModificationRequiredProductListRequestType getModificationRequiredProductListRequest);

    /**
     * 
     * @param restoreProductRequestType
     * @return
     *     returns com.nbp.nmp.shopn.restoreProductResponseType
     */
    @WebMethod(operationName = "RestoreProduct", action = "ProductService#RestoreProduct")
    @WebResult(name = "RestoreProductResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "RestoreProductResponse")
    public RestoreProductResponseType restoreProduct(
        @WebParam(name = "RestoreProductRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "RestoreProductRequest")
        RestoreProductRequestType restoreProductRequest);

    /**
     * 
     * @param changeProductSaleStatusRequestType
     * @return
     *     returns com.nbp.nmp.shopn.changeProductSaleStatusResponseType
     */
    @WebMethod(operationName = "ChangeProductSaleStatus", action = "ProductService#ChangeProductSaleStatus")
    @WebResult(name = "ChangeProductSaleStatusResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "ChangeProductSaleStatusResponse")
    public ChangeProductSaleStatusResponseType changeProductSaleStatus(
        @WebParam(name = "ChangeProductSaleStatusRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "ChangeProductSaleStatusRequest")
        ChangeProductSaleStatusRequestType changeProductSaleStatusRequest);
    
    
    
    /**
     * 
     * @param GetModelListRequestType2
     * @return
     *     returns com.nbp.nmp.shopn.GetModelListResponseType
     */
    @WebMethod(operationName = "GetModelList", action = "ProductService#GetModelList")
    @WebResult(name = "GetModelListResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetModelListResponse")
    public GetModelListResponseType getModelList2(
        @WebParam(name = "GetModelListRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetModelListRequest")
        GetModelListRequestType2 getModelListRequest);
    
}
