
package com.cware.api.panaver.product.type;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import com.cware.netshopping.common.util.ConfigUtil;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 03:56 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "QuestionAnswerService", targetNamespace = "http://shopn.platform.nhncorp.com/", wsdlLocation = "file:///home/himuleo/work/productapi-sample/src/main/resources/ShopNAPI.wsdl")
public class QuestionAnswerService
    extends Service
{

    private final static URL QUESTIONANSWERSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL(ConfigUtil.getString("PANAVER_SERVICE_WSDL"));
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        QUESTIONANSWERSERVICE_WSDL_LOCATION = url;
    }

    public QuestionAnswerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QuestionAnswerService() {
        super(QUESTIONANSWERSERVICE_WSDL_LOCATION, new QName("http://shopn.platform.nhncorp.com/", "QuestionAnswerService"));
    }

    /**
     * 
     * @return
     *     returns QuestionAnswerServicePortType
     */
    @WebEndpoint(name = "QuestionAnswerServiceSOAP11port_http")
    public QuestionAnswerServicePortType getQuestionAnswerServiceSOAP11PortHttp() {
        return (QuestionAnswerServicePortType)super.getPort(new QName("http://shopn.platform.nhncorp.com/", "QuestionAnswerServiceSOAP11port_http"), QuestionAnswerServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QuestionAnswerServicePortType
     */
    @WebEndpoint(name = "QuestionAnswerServiceSOAP11port_http")
    public QuestionAnswerServicePortType getQuestionAnswerServiceSOAP11PortHttp(WebServiceFeature... features) {
        return (QuestionAnswerServicePortType)super.getPort(new QName("http://shopn.platform.nhncorp.com/", "QuestionAnswerServiceSOAP11port_http"), QuestionAnswerServicePortType.class, features);
    }

    /**
     * 
     * @return
     *     returns QuestionAnswerServicePortType
     */
    @WebEndpoint(name = "QuestionAnswerServiceSOAP12port_http")
    public QuestionAnswerServicePortType getQuestionAnswerServiceSOAP12PortHttp() {
        return (QuestionAnswerServicePortType)super.getPort(new QName("http://shopn.platform.nhncorp.com/", "QuestionAnswerServiceSOAP12port_http"), QuestionAnswerServicePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QuestionAnswerServicePortType
     */
    @WebEndpoint(name = "QuestionAnswerServiceSOAP12port_http")
    public QuestionAnswerServicePortType getQuestionAnswerServiceSOAP12PortHttp(WebServiceFeature... features) {
        return (QuestionAnswerServicePortType)super.getPort(new QName("http://shopn.platform.nhncorp.com/", "QuestionAnswerServiceSOAP12port_http"), QuestionAnswerServicePortType.class, features);
    }

}
