
package com.cware.api.panaver.product.type;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 03:56 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebService(name = "QuestionAnswerServicePortType", targetNamespace = "http://shopn.platform.nhncorp.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface QuestionAnswerServicePortType {

    /**
     * 
     * @param getQuestionAnswerListRequest
     * @return
     *     returns com.nbp.nmp.shopn.GetQuestionAnswerListResponseType
     */
    @WebMethod(operationName = "GetQuestionAnswerList", action = "QuestionAnswerService#GetQuestionAnswerList")
    @WebResult(name = "GetQuestionAnswerListResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetQuestionAnswerListResponse")
    public GetQuestionAnswerListResponseType getQuestionAnswerList(
        @WebParam(name = "GetQuestionAnswerListRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "GetQuestionAnswerListRequest")
        GetQuestionAnswerListRequestType getQuestionAnswerListRequest);
    
    /**
     * 
     * @param manageQuestionAnswerRequest
     * @return
     *     returns com.nbp.nmp.shopn.ManageQuestionAnswerResponseType
     */
    @WebMethod(operationName = "ManageQuestionAnswer", action = "QuestionAnswerService#ManageQuestionAnswer")
    @WebResult(name = "ManageQuestionAnswerResponse", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "ManageQuestionAnswerResponse")
    public ManageQuestionAnswerResponseType manageQuestionAnswer(
    	@WebParam(name = "ManageQuestionAnswerRequest", targetNamespace = "http://shopn.platform.nhncorp.com/", partName = "ManageQuestionAnswerRequest")
    	ManageQuestionAnswerRequestType manageQuestionAnswerRequest);
}
